### ISSUE TITLE
SLEAS Letter attributes plugin

### ISSUE THREAD

**Issue by mohamednizar** [moe-lk/moe#2]
- [ ] Respective Letter No:
- [ ] PSC Letter No:
- [ ] PSC Letter Date:
- [ ] Working Place:
- [ ] Ministry, DoE, EP-  Division:
- [ ] Ministry , DoE , EP - Branch:
- [ ] National Schools - Province:
- [ ] National Schools - District:
- [ ] National Schools - Zone:
- [ ] National Schools - Division:
- [ ] National Schools - School:
- [ ] Province:
 
Refer for how to develop plugin:https://github.com/moe-lk/moe/blob/master/template-plugin.md

**Comment by Lmarcho** [comment]
>     * []  Respective Letter No:
> 
>     * [ ]  PSC Letter No:
> 
>     * [ ]  PSC Letter Date:
> 
>     * [ ]  Working Place:
> 
>     * [ ]  Ministry, DoE, EP-  Division:
> 
>     * [ ]  Ministry , DoE , EP - Branch:
> 
>     * [ ]  National Schools - Province:
> 
>     * [ ]  National Schools - District:
> 
>     * [ ]  National Schools - Zone:
> 
>     * [ ]  National Schools - Division:
> 
>     * [ ]  National Schools - School:
> 
>     * [ ]  Province:
> 
> 
> Refer for how to develop plugin:https://github.com/moe-lk/moe/blob/master/template-plugin.md

- [x] Respective Letter No:
- [x] PSC Letter Date:
- [x] Working Place:
- [x] Designation 
- [x] Working Branch
- [x] Respective Letter No Label:
- [x] Assume Date 
- [x] Appointed Date
