### ISSUE TITLE
Employee Registration

### ISSUE THREAD

**Issue by Dharshika9** [moe-lk/moe#30]
- [ ] Family Details Tab
      If the Employee  civil status ‘Single’ Family Details tab Disabled.

- [ ] Dynamic Error Messages

- [ ] Update Way of join
      In SLEAS General Service Details add 'Merit' to Way of Join

**Comment by Lmarcho** [comment]
- [x] Family Details Tab If the Employee civil status ‘Single’ Family Details tab Disabled.
- [ ] Dynamic Error Messages
- [x] Update Way of join In SLEAS General Service Details add 'Merit' to Way of Join
