### ISSUE TITLE
Placement Plugins

### ISSUE THREAD

**Issue by Dharshika9** [moe-lk/moe#32]
- [x] NIC

- [x] Grade

- [x] Title

- [x] Service

- [x] Previous Working Place

- [x] PSC Letter Date
   (Include PSC Letter Date filed in placement)

- [x] PSC Letter No

- [ ] Ref No

- [ ] Previous working place

@Lmarcho

**Comment by Lmarcho** [comment]
- [x] NIC
- [x] Grade
- [x] Title
- [ ] Service
- [ ] Previous Working Place
- [ ] PSC Letter Date
- [x] (Include PSC Letter Date filed in placement)
- [ ] PSC Letter No
- [x] Ref No
