### ISSUE TITLE
Add New Officer (Family Details) 

### ISSUE THREAD

**Issue by Dharshika9** [moe-lk/moe#49]
- [x] Include Religion Field in Spouse Details

- [x] Check whether can able to add multiple spouse details and successfully added to the Database

- [x] Check all the field validations

- [x] Check whether able to add multiple child details and successfully added to the Database
@Lmarcho @mohamednizar

**Comment by Lmarcho** [comment]
Done

**Comment by mohamednizar** [comment]
Good work guys.Please create a pull request with current changes
